# GUI parameters
feature_point_cloud_path: 'data/dianchang/saga/feature_training/final/feature_point_cloud.ply'
json_path: 'data/dianchang/saga/output.json'
quiet: false
window_height: 1080
window_width: 1920
