# Raw dataset paths (input data)
base_path: data/default
resolution: 1
eval: false
allow_principle_point_shift: false
images_path: '${.base_path}/fastRecon/dense/sparse/0/images'
sparse_path: '${.base_path}/fastRecon/dense/sparse/0'
depth_path: null
