classes: ['chair', 'table', 'plant', 'flower', 'foliage', 'tv', 'painting', 'sofa', 'cabinet', 'bed', 'wall', 'floor', 'ceiling', 'person', 'keyboard', 'door', 'window', 'lighting', 'book', 'socket', 'key', 'remote']
selected_classes: ['chair', 'table', 'plant', 'flower', 'foliage', 'tv', 'painting', 'sofa', 'cabinet', 'bed', 'keyboard', 'door', 'window', 'lighting', 'book', 'socket', 'key', 'remote']
feature_point_cloud_path: '${base_path}/contrastive_feature_point_cloud.ply'
json_path: '${base_path}/output.json'
progress_path: null
clean: false
quiet: false
k: 256
feature_ratio: 1.0
instance_threshold: 0.25
background_threshold: 0.5
scale_threshold: 0.8
opcity_threshold: 0.01
sample_num: -1