position_lr_init: 0.00016
position_lr_final: 0.0000016
position_lr_delay_mult: 0.01
position_lr_max_steps: 30_000
feature_lr: 0.0025
instance_feature_lr: 0.01
opacity_lr: 0.05
scaling_lr: 0.005
rotation_lr: 0.001
std_lr: 0.01
percent_dense: 0.01
lambda_dssim: 0.2
densification_interval: 100
opacity_reset_interval: 3000
densify_from_iter: 500
densify_until_iter: 15_000
densify_grad_threshold: 0.0002

# Training features
epochs: 10
sample_rate: 0.02
rfn: 1.
distance_weight: 1.
positive_weight: -1.
negative_weight: -1.
distance_sample_num: 1000

quiet: false
debug_from: -1
detect_anomaly: false
progress_path: null
point_cloud_path: '${base_path}/output_models/point_cloud/iteration_30000/point_cloud.ply'
feature_point_cloud_path: '${base_path}/contrastive_feature_point_cloud.ply'
tb_path: '${base_path}'